name = "tsoa-workers-example"
main = "src/server.ts"
compatibility_date = "2022-07-06"

account_id = "0c8c22bdcd98c3dc6a35190650ef7906"

kv_namespaces = []

[vars]
AUTH0_JWKS_URL = "https://auth.sesamy.dev/.well-known/jwks.json"